# Generated by Django 4.0.2 on 2022-02-18 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=20)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('annual_total_leave', models.IntegerField(default=0)),
                ('numberof_days', models.IntegerField()),
                ('leave_balance', models.IntegerField(blank=True, default=0)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('leave_comment', models.TextField()),
                ('leave_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.status')),
                ('leavetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.leavetype')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200)),
                ('dob', models.DateField()),
                ('emp_code', models.CharField(max_length=200)),
                ('emp_picture', models.ImageField(blank=True, upload_to='employee/pictures')),
                ('emp_address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(max_length=20)),
                ('emp_phone', models.CharField(max_length=200)),
                ('email_address', models.EmailField(blank=True, max_length=100)),
                ('emp_nationality', models.CharField(max_length=200)),
                ('started_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.department')),
                ('emp_gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.gender')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
