# Generated by Django 4.0.2 on 2022-02-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='annual_total_leave',
            field=models.IntegerField(default=21),
        ),
    ]
