# Generated by Django 4.0.2 on 2022-02-23 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_rename_leavetype_leave_leave_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='leave_type',
            new_name='leavetype',
        ),
    ]
