# Generated by Django 4.0.2 on 2022-02-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_rename_leave_type_leave_leavetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_code',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
